### ISSUE TITLE
Original repo maintained here: https://github.com/cba85/electron-webview

### ISSUE THREAD

**Issue by cba85** [genzyy/electron-webview#5]
You've just steal my work without forking it or even sending a PR.
Why don't you send me a pull request? 

Please, respect open-source and all its contributors.
At least, make a proper fork and mention my repo.

![UNADJUSTEDNONRAW_thumb_e9](https://user-images.githubusercontent.com/720547/147387162-18196c4f-15d3-4924-96e0-9b01959a33fb.jpg)

**Comment by genzyy** [comment]
Sir, first of all its not stealing your project, its forking your project. I created an issue on your project ([here](https://github.com/cba85/electron-webview/issues/50)) and when I started using your project it was not being maintained for a long time and had many issues opened and NOT FIXED. I wanted to help people who were using this project with updating it with latest updates and fixes. So I forked your repository and also mentioned [here](https://github.com/genzyy/electron-webview#source) that THIS REPO (mine repo) is a fork of YOUR REPO. Here I have stated everything SO PLEASE GET YOUR FACTS RIGHT BEFORE POINTING OUT. Saying all of this in a very friendly way and making sentences in caps so they are being highlighted.

Let me know if you want to know anything else I will help you with that. If you are satisfied with this I will close the issue.

Also if you have started maintaining your app again I will be very happy to create a pull request there.
Peace.

**Comment by genzyy** [comment]
And yeah Merry Christmas 🎄 !

**Comment by cba85** [comment]
> Sir, first of all its not stealing your project, its forking your project.

No you haven't fork my project. 

<img width="1217" alt="Screenshot 2021-12-25 at 15 26 28" src="https://user-images.githubusercontent.com/720547/147387101-1af505ad-145f-4f89-a347-9d09df2adeff.png">

That's not how fork works. Here how to fork a project : https://docs.github.com/en/get-started/quickstart/fork-a-repo
Hope it will help you!

> I created an issue on your project ([here](https://github.com/cba85/electron-webview/issues/50)) and when I started using your project it was not being maintained for a long time and had many issues opened and NOT FIXED. I wanted to help people who were using this project with updating it with latest updates and fixes. So I forked your repository and also mentioned [here](https://github.com/genzyy/electron-webview#source) that THIS REPO (mine repo) is a fork of YOUR REPO.

I maintained my repo for 4 years for free. So, yes, sometimes it takes time to update it. And that's why, in open-source world, you can contribute to project! Instead of just creating an issue (I've fixed today simply my updating Electron/remote package to 2.0, yup), you should have send me a pull request. I would just have to accept it and you'd be a contributor of my repo. Easy for me.

But I have to admit, and please accept my excuses for my mistake, I haven't see the credits you've added at the end of the project's README file. Thank you for that. It's just usually we fork project. Like that, the forked repository is mentioned at the top of GitHub repository page.

> Here I have stated everything SO PLEASE GET YOUR FACTS RIGHT BEFORE POINTING OUT. Saying all of this in a very friendly way and making sentences in caps so they are being highlighted.

My facts are rights. This comment is made to prove it. I don't need to write in caps, because I am right. Writing text in caps don't make them facts 😅

> Let me know if you want to know anything else I will help you with that. If you are satisfied with this I will close the issue.
> 
> Also if you have started maintaining your app again I will be very happy to create a pull request there. Peace.

Now, you're open to contribute to my work, and I'm glad to see it. I don't understand why you haven't contribute when you find the solution at your problem, but maybe it's Christmas spirit 🌲

I'm happy to find someone who will help the project I've started and maintained for 4 years :)

<img width="277" alt="Screenshot 2021-12-25 at 15 56 06" src="https://user-images.githubusercontent.com/720547/147387749-7daf2c02-f913-4b04-a338-7f31d4e8e7bf.png">

Merry Christmas!

**Comment by genzyy** [comment]
> My facts are rights. This comment is made to prove it. I don't need to write in caps, because I am right. Writing text in caps don't make them facts sweat_smile

LOL.

I am deleting the repo now.
