### ISSUE TITLE
Fork is not copy

### ISSUE THREAD

**Issue by cba85** [genzyy/electron-webview#6]
<img width="1217" alt="Screenshot 2021-12-25 at 15 26 28" src="https://user-images.githubusercontent.com/720547/147387101-1af505ad-145f-4f89-a347-9d09df2adeff.png">

![UNADJUSTEDNONRAW_thumb_e9](https://user-images.githubusercontent.com/720547/147387162-18196c4f-15d3-4924-96e0-9b01959a33fb.jpg)

**Comment by genzyy** [comment]
You denied your own issue lol ([here](https://github.com/genzyy/electron-webview/issues/5))

**Comment by cba85** [comment]
No you haven't fork my project. 

<img width="1217" alt="Screenshot 2021-12-25 at 15 26 28" src="https://user-images.githubusercontent.com/720547/147387101-1af505ad-145f-4f89-a347-9d09df2adeff.png">

That's not how fork works. Here how to fork a project : https://docs.github.com/en/get-started/quickstart/fork-a-repo
Hope it will help you!
